### PR TITLE
Removed dependency on JSON

### PR DESCRIPTION
**Pull request by dylanratcliffe**
Move JSON to multi JSON. This will use one of many JSON parsers depending on speed (nice).
It also means that we no longer need to have build tools installed on the PE masters because
now there are no dependencies that need compiling!!

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
@mikkergimenez This is the PR where I'd like to fix the tests if possible

**Comment by danielparks** [comment]
Looks like this has been rebased on #37. I left a comment on that PR with a suggestion about a simpler fix.

**Comment by rjpearce** [comment]
@danielparks After you merge this and #37 can you tag a new release please? :)

**Comment by danielparks** [comment]
I’m not sure why this thinks it can be merged… seems like it should conflict with the changes to #37 before it was merged. Could you rebase or merge master?

**Comment by dylanratcliffe** [comment]
@danielparks Okay rebased

**Comment by danielparks** [comment]
Nice. Looks good. Now let’s see if I can get it to release…

**Comment by danielparks** [comment]
It’s up! https://rubygems.org/gems/autosign

**Pull request merged**
